//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Locale {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BaseRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaseRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apps.Locale.BaseRes", typeof(BaseRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 分配角色 的本地化字符串。
        /// </summary>
        public static string AssignRole {
            get {
                return ResourceManager.GetString("AssignRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分配用户 的本地化字符串。
        /// </summary>
        public static string AssignUser {
            get {
                return ResourceManager.GetString("AssignUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核 的本地化字符串。
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核失败 的本地化字符串。
        /// </summary>
        public static string CheckFail {
            get {
                return ResourceManager.GetString("CheckFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核成功 的本地化字符串。
        /// </summary>
        public static string CheckSucceed {
            get {
                return ResourceManager.GetString("CheckSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}只能填写汉字 的本地化字符串。
        /// </summary>
        public static string ChinaCharExpression {
            get {
                return ResourceManager.GetString("ChinaCharExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 两次密码不一致 的本地化字符串。
        /// </summary>
        public static string ComparePassword {
            get {
                return ResourceManager.GetString("ComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必须包含字符串：{1} 的本地化字符串。
        /// </summary>
        public static string ContainExpression {
            get {
                return ResourceManager.GetString("ContainExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建 的本地化字符串。
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必须是日期格式：2012-10-10 的本地化字符串。
        /// </summary>
        public static string DateExpression {
            get {
                return ResourceManager.GetString("DateExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失败 的本地化字符串。
        /// </summary>
        public static string DeleteFail {
            get {
                return ResourceManager.GetString("DeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功 的本地化字符串。
        /// </summary>
        public static string DeleteSucceed {
            get {
                return ResourceManager.GetString("DeleteSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的桌面 的本地化字符串。
        /// </summary>
        public static string Desktop {
            get {
                return ResourceManager.GetString("Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详细 的本地化字符串。
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不可用 的本地化字符串。
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改失败 的本地化字符串。
        /// </summary>
        public static string EditFail {
            get {
                return ResourceManager.GetString("EditFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改成功 的本地化字符串。
        /// </summary>
        public static string EditSucceed {
            get {
                return ResourceManager.GetString("EditSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必须是邮箱地址 的本地化字符串。
        /// </summary>
        public static string EmailExpression {
            get {
                return ResourceManager.GetString("EmailExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建失败 的本地化字符串。
        /// </summary>
        public static string InsertFail {
            get {
                return ResourceManager.GetString("InsertFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建成功 的本地化字符串。
        /// </summary>
        public static string InsertSucceed {
            get {
                return ResourceManager.GetString("InsertSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必须在{1}和{2}之间 的本地化字符串。
        /// </summary>
        public static string IntRangeExpression {
            get {
                return ResourceManager.GetString("IntRangeExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}由字母,数字,划线,划线组成 的本地化字符串。
        /// </summary>
        public static string IsCharExpression {
            get {
                return ResourceManager.GetString("IsCharExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必须是一个浮点数 的本地化字符串。
        /// </summary>
        public static string IsDecimalExpression {
            get {
                return ResourceManager.GetString("IsDecimalExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必须是一个整数 的本地化字符串。
        /// </summary>
        public static string IsIntegerExpression {
            get {
                return ResourceManager.GetString("IsIntegerExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必须是一个浮负点数 的本地化字符串。
        /// </summary>
        public static string IsNegativeDecimalExpression {
            get {
                return ResourceManager.GetString("IsNegativeDecimalExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必须是一个负整数 的本地化字符串。
        /// </summary>
        public static string IsNegativeIntegerExpression {
            get {
                return ResourceManager.GetString("IsNegativeIntegerExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必须是一个数字 的本地化字符串。
        /// </summary>
        public static string IsNumberExpression {
            get {
                return ResourceManager.GetString("IsNumberExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必须是一个浮正点数 的本地化字符串。
        /// </summary>
        public static string IsPositiveDecimalExpression {
            get {
                return ResourceManager.GetString("IsPositiveDecimalExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必须是一个正整数 的本地化字符串。
        /// </summary>
        public static string IsPositiveIntegerExpression {
            get {
                return ResourceManager.GetString("IsPositiveIntegerExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}最多{1}个汉字,{2}个字符 的本地化字符串。
        /// </summary>
        public static string MaxWordsExpression {
            get {
                return ResourceManager.GetString("MaxWordsExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}最少{1}个字符 的本地化字符串。
        /// </summary>
        public static string MinWordsExpression {
            get {
                return ResourceManager.GetString("MinWordsExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必须不能包含字符串：{1} 的本地化字符串。
        /// </summary>
        public static string NotContainExpression {
            get {
                return ResourceManager.GetString("NotContainExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不能等同于{1} 的本地化字符串。
        /// </summary>
        public static string NotEqualExpression {
            get {
                return ResourceManager.GetString("NotEqualExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必须填写 的本地化字符串。
        /// </summary>
        public static string NotNullExpression {
            get {
                return ResourceManager.GetString("NotNullExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不是正确的电话号码,如：0769-2222222 的本地化字符串。
        /// </summary>
        public static string PhoneExpression {
            get {
                return ResourceManager.GetString("PhoneExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择要操作的记录 的本地化字符串。
        /// </summary>
        public static string PlaseChooseToOperatingRecords {
            get {
                return ResourceManager.GetString("PlaseChooseToOperatingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主键重复 的本地化字符串。
        /// </summary>
        public static string PrimaryRepeat {
            get {
                return ResourceManager.GetString("PrimaryRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        public static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重设密码 的本地化字符串。
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置失败 的本地化字符串。
        /// </summary>
        public static string SetFail {
            get {
                return ResourceManager.GetString("SetFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置成功 的本地化字符串。
        /// </summary>
        public static string SetSucceed {
            get {
                return ResourceManager.GetString("SetSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必须是网址,如：http://www.abc.com 的本地化字符串。
        /// </summary>
        public static string SiteExpression {
            get {
                return ResourceManager.GetString("SiteExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建人 的本地化字符串。
        /// </summary>
        public static string TitleCreatePerson {
            get {
                return ResourceManager.GetString("TitleCreatePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string TitleCreateTime {
            get {
                return ResourceManager.GetString("TitleCreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        public static string TitleEnable {
            get {
                return ResourceManager.GetString("TitleEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID 的本地化字符串。
        /// </summary>
        public static string TitleID {
            get {
                return ResourceManager.GetString("TitleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string TitleName {
            get {
                return ResourceManager.GetString("TitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说明 的本地化字符串。
        /// </summary>
        public static string TitleRemark {
            get {
                return ResourceManager.GetString("TitleRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 的本地化字符串。
        /// </summary>
        public static string TitleSort {
            get {
                return ResourceManager.GetString("TitleSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string TitleState {
            get {
                return ResourceManager.GetString("TitleState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反审核 的本地化字符串。
        /// </summary>
        public static string UnCheck {
            get {
                return ResourceManager.GetString("UnCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反审核失败 的本地化字符串。
        /// </summary>
        public static string UnCheckFail {
            get {
                return ResourceManager.GetString("UnCheckFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反审核成功 的本地化字符串。
        /// </summary>
        public static string UnCheckSucceed {
            get {
                return ResourceManager.GetString("UnCheckSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反选 的本地化字符串。
        /// </summary>
        public static string UnSelect {
            get {
                return ResourceManager.GetString("UnSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新失败 的本地化字符串。
        /// </summary>
        public static string UpdateFail {
            get {
                return ResourceManager.GetString("UpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新成功 的本地化字符串。
        /// </summary>
        public static string UpdateSucceed {
            get {
                return ResourceManager.GetString("UpdateSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你要删除所选择的记录吗？ 的本地化字符串。
        /// </summary>
        public static string YouWantToDeleteTheSelectedRecords {
            get {
                return ResourceManager.GetString("YouWantToDeleteTheSelectedRecords", resourceCulture);
            }
        }
    }
}
