//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Locale {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SysRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apps.Locale.SysRes", typeof(SysRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string SysAreas_CreateTime {
            get {
                return ResourceManager.GetString("SysAreas_CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Id 的本地化字符串。
        /// </summary>
        public static string SysAreas_Id {
            get {
                return ResourceManager.GetString("SysAreas_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string SysAreas_Name {
            get {
                return ResourceManager.GetString("SysAreas_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上级所属 的本地化字符串。
        /// </summary>
        public static string SysAreas_ParentId {
            get {
                return ResourceManager.GetString("SysAreas_ParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 的本地化字符串。
        /// </summary>
        public static string SysAreas_Sort {
            get {
                return ResourceManager.GetString("SysAreas_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string SysAreas_State {
            get {
                return ResourceManager.GetString("SysAreas_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生时间 的本地化字符串。
        /// </summary>
        public static string SysException_CreateTime {
            get {
                return ResourceManager.GetString("SysException_CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据 的本地化字符串。
        /// </summary>
        public static string SysException_Data {
            get {
                return ResourceManager.GetString("SysException_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助链接 的本地化字符串。
        /// </summary>
        public static string SysException_HelpLink {
            get {
                return ResourceManager.GetString("SysException_HelpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Id 的本地化字符串。
        /// </summary>
        public static string SysException_Id {
            get {
                return ResourceManager.GetString("SysException_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常信息 的本地化字符串。
        /// </summary>
        public static string SysException_Message {
            get {
                return ResourceManager.GetString("SysException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 来源 的本地化字符串。
        /// </summary>
        public static string SysException_Source {
            get {
                return ResourceManager.GetString("SysException_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 堆栈 的本地化字符串。
        /// </summary>
        public static string SysException_StackTrace {
            get {
                return ResourceManager.GetString("SysException_StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标 的本地化字符串。
        /// </summary>
        public static string SysException_TargetSite {
            get {
                return ResourceManager.GetString("SysException_TargetSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string SysLog_CreateTime {
            get {
                return ResourceManager.GetString("SysLog_CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Id 的本地化字符串。
        /// </summary>
        public static string SysLog_Id {
            get {
                return ResourceManager.GetString("SysLog_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作信息 的本地化字符串。
        /// </summary>
        public static string SysLog_Message {
            get {
                return ResourceManager.GetString("SysLog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块 的本地化字符串。
        /// </summary>
        public static string SysLog_Module {
            get {
                return ResourceManager.GetString("SysLog_Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作者 的本地化字符串。
        /// </summary>
        public static string SysLog_Operator {
            get {
                return ResourceManager.GetString("SysLog_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结果 的本地化字符串。
        /// </summary>
        public static string SysLog_Result {
            get {
                return ResourceManager.GetString("SysLog_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string SysLog_Type {
            get {
                return ResourceManager.GetString("SysLog_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建人 的本地化字符串。
        /// </summary>
        public static string SysModule_CreatePerson {
            get {
                return ResourceManager.GetString("SysModule_CreatePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string SysModule_CreateTime {
            get {
                return ResourceManager.GetString("SysModule_CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英文名称 的本地化字符串。
        /// </summary>
        public static string SysModule_EnglishName {
            get {
                return ResourceManager.GetString("SysModule_EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图标 的本地化字符串。
        /// </summary>
        public static string SysModule_Iconic {
            get {
                return ResourceManager.GetString("SysModule_Iconic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Id 的本地化字符串。
        /// </summary>
        public static string SysModule_Id {
            get {
                return ResourceManager.GetString("SysModule_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否最后一项 的本地化字符串。
        /// </summary>
        public static string SysModule_IsLast {
            get {
                return ResourceManager.GetString("SysModule_IsLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块名称 的本地化字符串。
        /// </summary>
        public static string SysModule_Name {
            get {
                return ResourceManager.GetString("SysModule_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上级模块 的本地化字符串。
        /// </summary>
        public static string SysModule_ParentId {
            get {
                return ResourceManager.GetString("SysModule_ParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说明 的本地化字符串。
        /// </summary>
        public static string SysModule_Remark {
            get {
                return ResourceManager.GetString("SysModule_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 的本地化字符串。
        /// </summary>
        public static string SysModule_Sort {
            get {
                return ResourceManager.GetString("SysModule_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否可用 的本地化字符串。
        /// </summary>
        public static string SysModule_State {
            get {
                return ResourceManager.GetString("SysModule_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超链接 的本地化字符串。
        /// </summary>
        public static string SysModule_Url {
            get {
                return ResourceManager.GetString("SysModule_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本号 的本地化字符串。
        /// </summary>
        public static string SysModule_Version {
            get {
                return ResourceManager.GetString("SysModule_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Id 的本地化字符串。
        /// </summary>
        public static string SysModuleOperate_Id {
            get {
                return ResourceManager.GetString("SysModuleOperate_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否验证 的本地化字符串。
        /// </summary>
        public static string SysModuleOperate_IsValid {
            get {
                return ResourceManager.GetString("SysModuleOperate_IsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作码 的本地化字符串。
        /// </summary>
        public static string SysModuleOperate_KeyCode {
            get {
                return ResourceManager.GetString("SysModuleOperate_KeyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块名称 的本地化字符串。
        /// </summary>
        public static string SysModuleOperate_ModuleId {
            get {
                return ResourceManager.GetString("SysModuleOperate_ModuleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string SysModuleOperate_Name {
            get {
                return ResourceManager.GetString("SysModuleOperate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 的本地化字符串。
        /// </summary>
        public static string SysModuleOperate_Sort {
            get {
                return ResourceManager.GetString("SysModuleOperate_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Id 的本地化字符串。
        /// </summary>
        public static string SysRight_Id {
            get {
                return ResourceManager.GetString("SysRight_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块Id 的本地化字符串。
        /// </summary>
        public static string SysRight_ModuleId {
            get {
                return ResourceManager.GetString("SysRight_ModuleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否有权限 的本地化字符串。
        /// </summary>
        public static string SysRight_Rightflag {
            get {
                return ResourceManager.GetString("SysRight_Rightflag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色Id 的本地化字符串。
        /// </summary>
        public static string SysRight_RoleId {
            get {
                return ResourceManager.GetString("SysRight_RoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Id 的本地化字符串。
        /// </summary>
        public static string SysRightOperate_Id {
            get {
                return ResourceManager.GetString("SysRightOperate_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否验证 的本地化字符串。
        /// </summary>
        public static string SysRightOperate_IsValid {
            get {
                return ResourceManager.GetString("SysRightOperate_IsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作码 的本地化字符串。
        /// </summary>
        public static string SysRightOperate_KeyCode {
            get {
                return ResourceManager.GetString("SysRightOperate_KeyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限Id 的本地化字符串。
        /// </summary>
        public static string SysRightOperate_RightId {
            get {
                return ResourceManager.GetString("SysRightOperate_RightId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建人 的本地化字符串。
        /// </summary>
        public static string SysRole_CreatePerson {
            get {
                return ResourceManager.GetString("SysRole_CreatePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string SysRole_CreateTime {
            get {
                return ResourceManager.GetString("SysRole_CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说明 的本地化字符串。
        /// </summary>
        public static string SysRole_Description {
            get {
                return ResourceManager.GetString("SysRole_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Id 的本地化字符串。
        /// </summary>
        public static string SysRole_Id {
            get {
                return ResourceManager.GetString("SysRole_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色名称 的本地化字符串。
        /// </summary>
        public static string SysRole_Name {
            get {
                return ResourceManager.GetString("SysRole_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户列表 的本地化字符串。
        /// </summary>
        public static string SysRole_UserName {
            get {
                return ResourceManager.GetString("SysRole_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 的本地化字符串。
        /// </summary>
        public static string SysRoleSysUser_SysRoleId {
            get {
                return ResourceManager.GetString("SysRoleSysUser_SysRoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        public static string SysRoleSysUser_SysUserId {
            get {
                return ResourceManager.GetString("SysRoleSysUser_SysUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年龄 的本地化字符串。
        /// </summary>
        public static string SysSample_Age {
            get {
                return ResourceManager.GetString("SysSample_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生日 的本地化字符串。
        /// </summary>
        public static string SysSample_Bir {
            get {
                return ResourceManager.GetString("SysSample_Bir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string SysSample_CreateTime {
            get {
                return ResourceManager.GetString("SysSample_CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID 的本地化字符串。
        /// </summary>
        public static string SysSample_Id {
            get {
                return ResourceManager.GetString("SysSample_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Id 的本地化字符串。
        /// </summary>
        public static string SysSample_Id1 {
            get {
                return ResourceManager.GetString("SysSample_Id1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string SysSample_Name {
            get {
                return ResourceManager.GetString("SysSample_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名 的本地化字符串。
        /// </summary>
        public static string SysSample_Name1 {
            get {
                return ResourceManager.GetString("SysSample_Name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string SysSample_Note {
            get {
                return ResourceManager.GetString("SysSample_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 照片 的本地化字符串。
        /// </summary>
        public static string SysSample_Photo {
            get {
                return ResourceManager.GetString("SysSample_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Id 的本地化字符串。
        /// </summary>
        public static string SysSettings_Id {
            get {
                return ResourceManager.GetString("SysSettings_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string SysSettings_Name {
            get {
                return ResourceManager.GetString("SysSettings_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值 的本地化字符串。
        /// </summary>
        public static string SysSettings_Parameter {
            get {
                return ResourceManager.GetString("SysSettings_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说明 的本地化字符串。
        /// </summary>
        public static string SysSettings_ReMark {
            get {
                return ResourceManager.GetString("SysSettings_ReMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string SysSettings_Type {
            get {
                return ResourceManager.GetString("SysSettings_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string SysStruct_CreateTime {
            get {
                return ResourceManager.GetString("SysStruct_CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上级管理 的本地化字符串。
        /// </summary>
        public static string SysStruct_Higher {
            get {
                return ResourceManager.GetString("SysStruct_Higher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Id 的本地化字符串。
        /// </summary>
        public static string SysStruct_Id {
            get {
                return ResourceManager.GetString("SysStruct_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string SysStruct_Name {
            get {
                return ResourceManager.GetString("SysStruct_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上级所属 的本地化字符串。
        /// </summary>
        public static string SysStruct_ParentId {
            get {
                return ResourceManager.GetString("SysStruct_ParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说名 的本地化字符串。
        /// </summary>
        public static string SysStruct_Remark {
            get {
                return ResourceManager.GetString("SysStruct_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 的本地化字符串。
        /// </summary>
        public static string SysStruct_Sort {
            get {
                return ResourceManager.GetString("SysStruct_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string SysStruct_State {
            get {
                return ResourceManager.GetString("SysStruct_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详细地址 的本地化字符串。
        /// </summary>
        public static string SysUser_Address {
            get {
                return ResourceManager.GetString("SysUser_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附件 的本地化字符串。
        /// </summary>
        public static string SysUser_Attach {
            get {
                return ResourceManager.GetString("SysUser_Attach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生日 的本地化字符串。
        /// </summary>
        public static string SysUser_Birthday {
            get {
                return ResourceManager.GetString("SysUser_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效证件 的本地化字符串。
        /// </summary>
        public static string SysUser_Card {
            get {
                return ResourceManager.GetString("SysUser_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 城市 的本地化字符串。
        /// </summary>
        public static string SysUser_City {
            get {
                return ResourceManager.GetString("SysUser_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建人 的本地化字符串。
        /// </summary>
        public static string SysUser_CreatePerson {
            get {
                return ResourceManager.GetString("SysUser_CreatePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string SysUser_CreateTime {
            get {
                return ResourceManager.GetString("SysUser_CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 学历 的本地化字符串。
        /// </summary>
        public static string SysUser_Degree {
            get {
                return ResourceManager.GetString("SysUser_Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门 的本地化字符串。
        /// </summary>
        public static string SysUser_DepId {
            get {
                return ResourceManager.GetString("SysUser_DepId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮件地址 的本地化字符串。
        /// </summary>
        public static string SysUser_EmailAddress {
            get {
                return ResourceManager.GetString("SysUser_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人简介 的本地化字符串。
        /// </summary>
        public static string SysUser_Expertise {
            get {
                return ResourceManager.GetString("SysUser_Expertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Id 的本地化字符串。
        /// </summary>
        public static string SysUser_Id {
            get {
                return ResourceManager.GetString("SysUser_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职位状态 的本地化字符串。
        /// </summary>
        public static string SysUser_JobState {
            get {
                return ResourceManager.GetString("SysUser_JobState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入职日期 的本地化字符串。
        /// </summary>
        public static string SysUser_JoinDate {
            get {
                return ResourceManager.GetString("SysUser_JoinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 婚姻状况 的本地化字符串。
        /// </summary>
        public static string SysUser_Marital {
            get {
                return ResourceManager.GetString("SysUser_Marital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机 的本地化字符串。
        /// </summary>
        public static string SysUser_MobileNumber {
            get {
                return ResourceManager.GetString("SysUser_MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 民族 的本地化字符串。
        /// </summary>
        public static string SysUser_Nationality {
            get {
                return ResourceManager.GetString("SysUser_Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 籍贯 的本地化字符串。
        /// </summary>
        public static string SysUser_Native {
            get {
                return ResourceManager.GetString("SysUser_Native", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他联系方式 的本地化字符串。
        /// </summary>
        public static string SysUser_OtherContact {
            get {
                return ResourceManager.GetString("SysUser_OtherContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string SysUser_Password {
            get {
                return ResourceManager.GetString("SysUser_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话 的本地化字符串。
        /// </summary>
        public static string SysUser_PhoneNumber {
            get {
                return ResourceManager.GetString("SysUser_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 照片 的本地化字符串。
        /// </summary>
        public static string SysUser_Photo {
            get {
                return ResourceManager.GetString("SysUser_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 党派 的本地化字符串。
        /// </summary>
        public static string SysUser_Political {
            get {
                return ResourceManager.GetString("SysUser_Political", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职位 的本地化字符串。
        /// </summary>
        public static string SysUser_PosId {
            get {
                return ResourceManager.GetString("SysUser_PosId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 专业 的本地化字符串。
        /// </summary>
        public static string SysUser_Professional {
            get {
                return ResourceManager.GetString("SysUser_Professional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 省份 的本地化字符串。
        /// </summary>
        public static string SysUser_Province {
            get {
                return ResourceManager.GetString("SysUser_Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QQ 的本地化字符串。
        /// </summary>
        public static string SysUser_QQ {
            get {
                return ResourceManager.GetString("SysUser_QQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色列表 的本地化字符串。
        /// </summary>
        public static string SysUser_RoleName {
            get {
                return ResourceManager.GetString("SysUser_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 就读学校 的本地化字符串。
        /// </summary>
        public static string SysUser_School {
            get {
                return ResourceManager.GetString("SysUser_School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性别 的本地化字符串。
        /// </summary>
        public static string SysUser_Sex {
            get {
                return ResourceManager.GetString("SysUser_Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号状态 的本地化字符串。
        /// </summary>
        public static string SysUser_State {
            get {
                return ResourceManager.GetString("SysUser_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 真实姓名 的本地化字符串。
        /// </summary>
        public static string SysUser_TrueName {
            get {
                return ResourceManager.GetString("SysUser_TrueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string SysUser_UserName {
            get {
                return ResourceManager.GetString("SysUser_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域 的本地化字符串。
        /// </summary>
        public static string SysUser_Village {
            get {
                return ResourceManager.GetString("SysUser_Village", resourceCulture);
            }
        }
    }
}
